#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PhoneTag.XamarinForms.Droid.Resource", IsApplication=true)]

namespace PhoneTag.XamarinForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::PhoneTag.XamarinForms.Droid.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::PhoneTag.XamarinForms.Droid.Resource.String.library_name;
			global::PCLStorage.Resource.String.ApplicationName = global::PhoneTag.XamarinForms.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PhoneTag.XamarinForms.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::PhoneTag.XamarinForms.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_friend_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int attack = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_short = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int create_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exit_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int friend_indication = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int friend_menu_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int heart = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int killcam_frame = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int loading_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int loading_logo_1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int loading_logo_10 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int loading_logo_11 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int loading_logo_12 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int loading_logo_13 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int loading_logo_14 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int loading_logo_15 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int loading_logo_16 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int loading_logo_17 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int loading_logo_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int loading_logo_19 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int loading_logo_2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int loading_logo_20 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int loading_logo_21 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int loading_logo_22 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int loading_logo_23 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int loading_logo_24 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int loading_logo_25 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int loading_logo_26 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int loading_logo_27 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int loading_logo_28 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int loading_logo_29 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int loading_logo_3 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int loading_logo_30 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int loading_logo_4 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int loading_logo_5 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int loading_logo_6 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int loading_logo_7 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int loading_logo_8 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int loading_logo_9 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int mainmenu_background = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int myself = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int protect = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int protect_me = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int search_button = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int settings_button = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int shoot_button = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int switchCameraButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int takePhotoButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int textureView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int toggleFlashButton = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
