#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PhoneTag.XamarinForms.Droid.Resource", IsApplication=true)]

namespace PhoneTag.XamarinForms.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::PhoneTag.XamarinForms.Droid.Resource.String.library_name;
			global::Gcm.Client.Resource.String.library_name = global::PhoneTag.XamarinForms.Droid.Resource.String.library_name;
			global::PCLStorage.Resource.String.ApplicationName = global::PhoneTag.XamarinForms.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PhoneTag.XamarinForms.Droid.Resource.String.Hello;
			//global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::PhoneTag.XamarinForms.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_friend_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int friend_indication = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int friend_menu_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int switchCameraButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int takePhotoButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int textureView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int toggleFlashButton = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
